# Generated by Django 4.0.5 on 2022-06-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Breastmilk Thieves', max_length=42, unique=True)),
                ('developer', models.CharField(default='Activision Blizzard', max_length=32)),
                ('publisher', models.CharField(default='Activision Blizzard', max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=72)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('prizing', models.IntegerField(default=69)),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
                ('revision_count', models.IntegerField(default=0)),
            ],
        ),
    ]
